<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="8" failed="0" total="10" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Canopy Enterprise Platform Functional Test Result" duration-ms="0" started-at="2015-02-28T10:35:16Z" finished-at="2015-02-28T10:35:16Z">
    <groups>
    </groups>
  </suite>
  <suite name="Suite B" duration-ms="2806" started-at="2015-02-28T10:35:06Z" finished-at="2015-02-28T10:35:08Z">
    <groups>
    </groups>
    <test name="Test 1" duration-ms="1580" started-at="2015-02-28T10:35:06Z" finished-at="2015-02-28T10:35:07Z">
      <class name="com.canopy.framework.datadriven.suiteB.Test1">
        <test-method status="SKIP" signature="test1(java.util.Hashtable)" name="test1" duration-ms="450" started-at="2015-02-28T10:35:06Z" finished-at="2015-02-28T10:35:06Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Col3=DummyA3, Col2=DummyA2, Col1=DummyA1, Runmode=Y, Result=}]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Skipping the test Test1 inside the suite SuiteB]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Skipping the test Test1 inside the suite SuiteB
	at com.canopy.framework.datadriven.TestBase.validateRunmodes(TestBase.java:80)
	at com.canopy.framework.datadriven.suiteB.Test1.test1(Test1.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:673)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:842)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1166)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.runWorkers(TestRunner.java:1178)
	at org.testng.TestRunner.privateRun(TestRunner.java:757)
	at org.testng.TestRunner.run(TestRunner.java:608)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1158)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1154)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1083)
	at org.testng.TestNG.run(TestNG.java:999)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:203)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:174)
]]>
            </full-stacktrace>
          </exception>
        </test-method>
        <test-method status="SKIP" signature="test1(java.util.Hashtable)" name="test1" duration-ms="415" started-at="2015-02-28T10:35:06Z" finished-at="2015-02-28T10:35:07Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Col3=DummyA6, Col2=DummyA5, Col1=DummyA4, Runmode=N, Result=}]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Skipping the test Test1 inside the suite SuiteB]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Skipping the test Test1 inside the suite SuiteB
	at com.canopy.framework.datadriven.TestBase.validateRunmodes(TestBase.java:80)
	at com.canopy.framework.datadriven.suiteB.Test1.test1(Test1.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:673)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:842)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1166)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.runWorkers(TestRunner.java:1178)
	at org.testng.TestRunner.privateRun(TestRunner.java:757)
	at org.testng.TestRunner.run(TestRunner.java:608)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1158)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1154)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1083)
	at org.testng.TestNG.run(TestNG.java:999)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:203)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:174)
]]>
            </full-stacktrace>
          </exception>
        </test-method>
        <test-method status="SKIP" signature="test1(java.util.Hashtable)" name="test1" duration-ms="456" started-at="2015-02-28T10:35:07Z" finished-at="2015-02-28T10:35:07Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Col3=DummyA9, Col2=DummyA8, Col1=DummyA7, Runmode=Y, Result=}]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Skipping the test Test1 inside the suite SuiteB]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Skipping the test Test1 inside the suite SuiteB
	at com.canopy.framework.datadriven.TestBase.validateRunmodes(TestBase.java:80)
	at com.canopy.framework.datadriven.suiteB.Test1.test1(Test1.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:673)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:842)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1166)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.runWorkers(TestRunner.java:1178)
	at org.testng.TestRunner.privateRun(TestRunner.java:757)
	at org.testng.TestRunner.run(TestRunner.java:608)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1158)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1154)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1083)
	at org.testng.TestNG.run(TestNG.java:999)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:203)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:174)
]]>
            </full-stacktrace>
          </exception>
        </test-method>
      </class>
    </test>
    <test name="Test 2" duration-ms="1166" started-at="2015-02-28T10:35:07Z" finished-at="2015-02-28T10:35:08Z">
      <class name="com.canopy.framework.datadriven.suiteB.Test2">
        <test-method status="SKIP" signature="test2(java.util.Hashtable)" name="test2" duration-ms="475" started-at="2015-02-28T10:35:07Z" finished-at="2015-02-28T10:35:08Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Col5=DA14, Col4=DA13, Col3=DA12, Col2=DA11, Col1=DA10, Runmode=N, Result=}]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Skipping the test Test2 inside the suite SuiteB]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Skipping the test Test2 inside the suite SuiteB
	at com.canopy.framework.datadriven.TestBase.validateRunmodes(TestBase.java:80)
	at com.canopy.framework.datadriven.suiteB.Test2.test2(Test2.java:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:673)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:842)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1166)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.runWorkers(TestRunner.java:1178)
	at org.testng.TestRunner.privateRun(TestRunner.java:757)
	at org.testng.TestRunner.run(TestRunner.java:608)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1158)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1154)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1083)
	at org.testng.TestNG.run(TestNG.java:999)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:203)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:174)
]]>
            </full-stacktrace>
          </exception>
        </test-method>
        <test-method status="SKIP" signature="test2(java.util.Hashtable)" name="test2" duration-ms="456" started-at="2015-02-28T10:35:08Z" finished-at="2015-02-28T10:35:08Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Col5=DA19, Col4=DA18, Col3=DA17, Col2=DA16, Col1=DA15, Runmode=Y, Result=}]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Skipping the test Test2 inside the suite SuiteB]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Skipping the test Test2 inside the suite SuiteB
	at com.canopy.framework.datadriven.TestBase.validateRunmodes(TestBase.java:80)
	at com.canopy.framework.datadriven.suiteB.Test2.test2(Test2.java:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:673)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:842)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1166)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.runWorkers(TestRunner.java:1178)
	at org.testng.TestRunner.privateRun(TestRunner.java:757)
	at org.testng.TestRunner.run(TestRunner.java:608)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1158)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1154)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1083)
	at org.testng.TestNG.run(TestNG.java:999)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:203)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:174)
]]>
            </full-stacktrace>
          </exception>
        </test-method>
      </class>
    </test>
  </suite>
  <suite name="Market Place Tests" duration-ms="205380" started-at="2015-02-28T10:31:33Z" finished-at="2015-02-28T10:34:59Z">
    <groups>
    </groups>
    <test name="Login Test" duration-ms="105184" started-at="2015-02-28T10:31:33Z" finished-at="2015-02-28T10:33:19Z">
      <class name="com.canopy.framework.datadriven.MarketPlaceSuite.LoginTest">
        <test-method status="PASS" signature="initLogs()" name="initLogs" is-config="true" duration-ms="65" started-at="2015-02-28T10:31:34Z" finished-at="2015-02-28T10:31:34Z">
        </test-method>
        <test-method status="PASS" signature="loginTest(java.util.Hashtable)" name="loginTest" duration-ms="100796" started-at="2015-02-28T10:31:35Z" finished-at="2015-02-28T10:33:16Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Username=admin.cep@yopmail.com, Password=Canopy1!, Runmode=Y, Expected_Result=SUCCESS, Browser=Chrome, Result=}]]>
              </value>
            </param>
          </params>
        </test-method>
        <test-method status="PASS" signature="close()" name="close" is-config="true" duration-ms="1627" started-at="2015-02-28T10:33:16Z" finished-at="2015-02-28T10:33:18Z">
        </test-method>
        <test-method status="SKIP" signature="loginTest(java.util.Hashtable)" name="loginTest" duration-ms="641" started-at="2015-02-28T10:33:18Z" finished-at="2015-02-28T10:33:18Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Username=DummyA4, Password=DummyA5, Runmode=N, Expected_Result=FAILURE, Browser=Chrome, Result=}]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Skipping the test loginTest inside the suite MarketPlaceSuite]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Skipping the test loginTest inside the suite MarketPlaceSuite
	at com.canopy.framework.datadriven.TestBase.validateRunmodes(TestBase.java:80)
	at com.canopy.framework.datadriven.MarketPlaceSuite.LoginTest.loginTest(LoginTest.java:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:673)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:842)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1166)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.runWorkers(TestRunner.java:1178)
	at org.testng.TestRunner.privateRun(TestRunner.java:757)
	at org.testng.TestRunner.run(TestRunner.java:608)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1158)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1154)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1083)
	at org.testng.TestNG.run(TestNG.java:999)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:203)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:174)
]]>
            </full-stacktrace>
          </exception>
        </test-method>
        <test-method status="SKIP" signature="loginTest(java.util.Hashtable)" name="loginTest" duration-ms="492" started-at="2015-02-28T10:33:18Z" finished-at="2015-02-28T10:33:19Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Username=DummyA7, Password=DummyA8, Runmode=N, Expected_Result=FAILURE, Browser=Mozilla, Result=}]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Skipping the test loginTest inside the suite MarketPlaceSuite]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Skipping the test loginTest inside the suite MarketPlaceSuite
	at com.canopy.framework.datadriven.TestBase.validateRunmodes(TestBase.java:80)
	at com.canopy.framework.datadriven.MarketPlaceSuite.LoginTest.loginTest(LoginTest.java:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:673)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:842)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1166)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.runWorkers(TestRunner.java:1178)
	at org.testng.TestRunner.privateRun(TestRunner.java:757)
	at org.testng.TestRunner.run(TestRunner.java:608)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1158)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1154)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1083)
	at org.testng.TestNG.run(TestNG.java:999)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:203)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:174)
]]>
            </full-stacktrace>
          </exception>
        </test-method>
        <test-method status="PASS" signature="close()" name="close" is-config="true" duration-ms="0" started-at="2015-02-28T10:33:18Z" finished-at="2015-02-28T10:33:18Z">
        </test-method>
        <test-method status="PASS" signature="close()" name="close" is-config="true" duration-ms="0" started-at="2015-02-28T10:33:19Z" finished-at="2015-02-28T10:33:19Z">
        </test-method>
      </class>
    </test>
    <test name="Test 2" duration-ms="99931" started-at="2015-02-28T10:33:19Z" finished-at="2015-02-28T10:34:59Z">
      <class name="com.canopy.framework.datadriven.MarketPlaceSuite.Test2">
        <test-method status="PASS" signature="initLogs()" name="initLogs" is-config="true" duration-ms="0" started-at="2015-02-28T10:33:19Z" finished-at="2015-02-28T10:33:19Z">
        </test-method>
        <test-method status="PASS" signature="test2(java.util.Hashtable)" name="test2" duration-ms="97673" started-at="2015-02-28T10:33:19Z" finished-at="2015-02-28T10:34:57Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Runmode=Y, Expected_Result=SUCCESS, Browser=Chrome, Result=}]]>
              </value>
            </param>
          </params>
        </test-method>
        <test-method status="PASS" signature="close()" name="close" is-config="true" duration-ms="1446" started-at="2015-02-28T10:34:57Z" finished-at="2015-02-28T10:34:58Z">
        </test-method>
        <test-method status="SKIP" signature="test2(java.util.Hashtable)" name="test2" duration-ms="521" started-at="2015-02-28T10:34:58Z" finished-at="2015-02-28T10:34:59Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Runmode=N, Expected_Result=FAILURE, Browser=Mozilla, Result=}]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Skipping the test Test2 inside the suite MarketPlaceSuite]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Skipping the test Test2 inside the suite MarketPlaceSuite
	at com.canopy.framework.datadriven.TestBase.validateRunmodes(TestBase.java:80)
	at com.canopy.framework.datadriven.MarketPlaceSuite.Test2.test2(Test2.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:673)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:842)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1166)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.runWorkers(TestRunner.java:1178)
	at org.testng.TestRunner.privateRun(TestRunner.java:757)
	at org.testng.TestRunner.run(TestRunner.java:608)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1158)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1154)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1083)
	at org.testng.TestNG.run(TestNG.java:999)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:203)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:174)
]]>
            </full-stacktrace>
          </exception>
        </test-method>
        <test-method status="PASS" signature="close()" name="close" is-config="true" duration-ms="0" started-at="2015-02-28T10:34:59Z" finished-at="2015-02-28T10:34:59Z">
        </test-method>
      </class>
    </test>
  </suite>
</testng-results>
